server:
  port: 8081

spring:
  application:
    name: autoagent

  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: autoagent-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDesialization
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserialzer
      properties:
        spring.json.trusted.packages: "*"
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

nasa:
  api:
    key: "coxlJ9fYTtxBjr1S5jUAtb0VbwZD9qy2zVccm6AQ"
    base-url: "https://api.nasa.gov"
